### ISSUE TITLE
Overall Nova Pro experience on Linux

### ISSUE THREAD

**Issue by podiki** [Dymstro/nova-chatmix-linux#2]
Apologies for the "not an issue" topic here. I was curious overall how well (or not) the Nova Pro Wireless works on Linux? Other reports I saw online said it was a big step backwards from the Pro Wireless it replaced, as more needed to be done in software rather than through the hardware hub. This was the only project I saw for changing the chat mix, but what about anything else that is still missing from the Linux experience? What features don't work?

Thanks!

**Comment by Dymstro** [comment]
As far as I know chatmix is the only thing missing on linux compared to older headsets.

I've never really used Sonar outside of figuring out how the chatmix controls work, so I don't really know what other features it provides. I do know it enables some kind of virtual surround sound implementation, but I've never really been a fan of those. 

Other settings like EQ can be set using the base station itself (although i think Sonar can disable the hardware EQ if it's running).

**Comment by podiki** [comment]
Thanks!
